on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  FUNCTION_NAME: nhs_reverification_hello_world
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out your repository under 'GITHUB_WORKSPACE' (so workflow can access it)
        uses: actions/checkout@v2
      - name: Set up a Python environment for use in actions
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy function with dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -t ./$FUNCTION_NAME/package -r ./$FUNCTION_NAME/requirements.txt
          cd ./$FUNCTION_NAME/package
          zip -r ../deploy.zip .
          cd ..
          zip -g deploy.zip lambda_function.py
          aws lambda update-function-code --function-name=$FUNCTION_NAME --zip-file=fileb://deploy.zip --region $AWS_REGION
