name: Build and deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
env:
  AWS_REGION: us-east-1
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function-name: ['nhs_reverification_hello_world', 'nhs_reverification_notify']
    steps:
      - name: Check-out your repository under 'GITHUB_WORKSPACE' (so workflow can access it)
        uses: actions/checkout@v2
      - name: Set up a Python environment for use in actions
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: "pip"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy ${{ matrix.function-name }} function with dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -t ./${{ matrix.function-name }}/package -r ./${{ matrix.function-name }}/requirements.txt
          cd ./${{ matrix.function-name }}/package
          zip -r ../deploy.zip .
          cd ..
          zip -g deploy.zip *.py
          aws lambda update-function-code --function-name=${{ matrix.function-name }} --zip-file=fileb://deploy.zip --region $AWS_REGION
