on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-west-1
  AWS_S3_BUCKET: nhs-verification-poc-sample-bucket
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      # sam build 
      - run: sam build --use-container
      # sam deploy
      - run: yes | sam delete --stack-name aws-sam-cli-managed-default
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --s3-bucket $AWS_S3_BUCKET --stack-name sam-hello-world --capabilities CAPABILITY_IAM --region $AWS_REGION