on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out your repository under 'GITHUB_WORKSPACE' (so workflow can access it)
        uses: actions/checkout@v2
      - name: Set up a Python environment for use in actions
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: deploy
        run: |
          zip -j deploy.zip ./* #--> Zip the Code As we know lambda function accept the zip file.
          aws lambda update-function-code --function-name=nhs_reverification_hello_world --zip-file=fileb://deploy.zip --region $AWS_REGION