name: Run unit tests
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Set up a Python environment for use in actions
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: "pip"
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run 'nhs_reverification_hello_world' tests
        run: |
          pip install -t ./${{env.function_name}}/unit_tests/package -r ./${{env.function_name}}/unit_tests/requirements.txt
          pytest ./${{env.function_name}}/unit_tests/*.py
        env:
          function_name: nhs_reverification_hello_world
      - name: Run 'nhs_reverification_notify' tests
        run: |
          pip install -t ./${{env.function_name}}/unit_tests/package -r ./${{env.function_name}}/unit_tests/requirements.txt
          pytest ./${{env.function_name}}/unit_tests/*.py
        env:
          function_name: nhs_reverification_notify
