name: Run unit tests
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Set up a Python environment for use in actions
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: "pip"
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run 'nhs_reverification_hello_world' test
        run: |
          cd ./nhs_reverification_hello_world/unit_tests
          pip install -t ./nhs_reverification_hello_world/unit_tests/package -r ./nhs_reverification_hello_world/unit_tests/requirements.txt
          pytest ./nhs_reverification_hello_world/unit_tests/*.py
